image: node:20

stages:
  - build
  - deploy

cache: {}

build:
  stage: build
  script:
    - rm -rf node_modules package-lock.json
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
      - package-lock.json

pages:
  stage: deploy
  script:
    - mkdir public
    - rsync -av dist/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
